/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author NEW
 */
public class UserProfileUI extends javax.swing.JFrame {

    /**
     * Creates new form UserProfileUI
     */
    public UserProfileUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_OK = new javax.swing.JButton();
        Field_Name = new javax.swing.JTextField();
        Field_LastName = new javax.swing.JTextField();
        Field_Email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("ชื่อ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 120, 50, 14);

        jLabel2.setText("นามสกุล");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 160, 80, 14);

        jLabel3.setText("ที่อยู่");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(143, 190, 60, 14);

        jLabel4.setText("อีเมลล์");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(144, 271, 70, 14);

        jButton_OK.setText("ตกลง");
        getContentPane().add(jButton_OK);
        jButton_OK.setBounds(290, 300, 80, 23);
        getContentPane().add(Field_Name);
        Field_Name.setBounds(230, 114, 212, 20);
        getContentPane().add(Field_LastName);
        Field_LastName.setBounds(230, 152, 209, 20);
        getContentPane().add(Field_Email);
        Field_Email.setBounds(230, 270, 210, 20);

        jTextArea_Address.setColumns(20);
        jTextArea_Address.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 190, 209, 67);

        setSize(new java.awt.Dimension(616, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfileUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Field_Email;
    private javax.swing.JTextField Field_LastName;
    private javax.swing.JTextField Field_Name;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Address;
    // End of variables declaration//GEN-END:variables
}
